---
abstract: 'Stop, start and monitor your slaves.'
author:
  - 'Olaf Alders <olaf@wundercounter.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100922'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-MySQL-Replication-Slave
recommends: {}
requires:
  DBD::mysql: 0
  Moose: 0
resources:
  repository: http://github.com/oalders/dbix-mysql-replication-slave
version: 0.01
